name = "pulsetrack-app"
compatibility_date = "2024-04-01"
pages_build_output_dir = "public"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "pulsetrack_db"
database_id = "daa8d8e8-f47f-44f4-b89a-9cf8086fd480"
